apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: http-app
  name: http-app
spec:
  selector:
    matchLabels:
      app: http-app
  template:
    metadata:
      labels:
        app: http-app
    spec:
      containers:
      - image: node:lts-alpine3.14
        name: user-container
        command:
          - "node"
          - "-e"
        args:
        - |
          const http = require('http');
          const options = {}
          http.createServer(options, (req, res) => {
            res.writeHead(200);
            res.end('hello world\n');
          }).listen(8000);
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: http-app
  name: http-app
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: http-app
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: http-app
  name: http-app
spec:
  port:
    targetPort: 8000
  to:
    kind: Service
    name: http-app
